version: '1.0'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
